-- ============================================================
-- VoteCore: Relational Database Schema (Oracle Database 21c)
-- Capstone Project — National Institute of Technology Warangal
-- ============================================================

-- Cleanup existing tables (Reverse dependency order)
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables 
        WHERE table_name IN (
            'FRAUD_LOGS', 'AUDIT_LOGS', 'VOTE_RESULTS', 'VOTE', 
            'EVENT_PARTICIPANTS', 'CANDIDATE', 'ELECTION', 'ORG_SCOPE', 
            'MEMBER_ROLES', 'ORG_MEMBERS', 'ROLE', 'ORGANIZATION', 
            'USER_SESSIONS', 'OTP_VERIFICATION', 'IDENTITY_WALLET', 
            'GOV_IDENTITY', 'UACCOUNT'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ------------------------------------------------------------
-- 1. UACCOUNT (Core User Account Registry)
-- ------------------------------------------------------------
CREATE TABLE UACCOUNT (
    PID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME      VARCHAR2(80) NOT NULL,
    LAST_NAME       VARCHAR2(80) NOT NULL,
    MOBILE          VARCHAR2(15) NOT NULL,
    EMAIL           VARCHAR2(254) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(255) NOT NULL,
    COUNTRY         VARCHAR2(80) DEFAULT 'India',
    STATE           VARCHAR2(80),
    IS_ACTIVE       NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ------------------------------------------------------------
-- 2. GOV_IDENTITY (Verified Government Credentials — Encrypted/Hashed)
-- ------------------------------------------------------------
CREATE TABLE GOV_IDENTITY (
    GOV_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER NOT NULL UNIQUE,
    EPIC_ID         VARCHAR2(255) NOT NULL,
    AADHAAR_NO      VARCHAR2(255),
    FULL_NAME       VARCHAR2(160) NOT NULL,
    DOB             DATE NOT NULL,
    IS_VERIFIED     NUMBER(1) DEFAULT 1 CHECK (IS_VERIFIED IN (0, 1)),
    VERIFIED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_GOV_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 3. IDENTITY_WALLET (Federated Identity Mapping Layer)
-- ------------------------------------------------------------
CREATE TABLE IDENTITY_WALLET (
    WALLET_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER NOT NULL,
    IDENTITY_TYPE   VARCHAR2(50) DEFAULT 'GOV' NOT NULL,
    EPIC_ID         VARCHAR2(255) NOT NULL,
    LINKED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_WALLET_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 4. OTP_VERIFICATION (Two-Factor Authentication Passcodes)
-- ------------------------------------------------------------
CREATE TABLE OTP_VERIFICATION (
    OTP_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER NOT NULL,
    OTP_CODE        VARCHAR2(10) NOT NULL,
    VERIFIED        NUMBER(1) DEFAULT 0 CHECK (VERIFIED IN (0, 1)),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRES_AT      TIMESTAMP NOT NULL,
    CONSTRAINT FK_OTP_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 5. USER_SESSIONS (Stateful Database Session Validation)
-- ------------------------------------------------------------
CREATE TABLE USER_SESSIONS (
    SESSION_ID      VARCHAR2(100) PRIMARY KEY,
    PID             NUMBER NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRES_AT      TIMESTAMP NOT NULL,
    IS_ACTIVE       NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT FK_SESSION_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 6. ORGANIZATION (Multi-Tenant Entities)
-- ------------------------------------------------------------
CREATE TABLE ORGANIZATION (
    ORGID           VARCHAR2(40) PRIMARY KEY,
    ORG_NAME        VARCHAR2(160) NOT NULL,
    ORG_EMAIL       VARCHAR2(254) NOT NULL,
    IS_ACTIVE       NUMBER(1) DEFAULT 0 CHECK (IS_ACTIVE IN (0, 1)),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ------------------------------------------------------------
-- 7. ROLE (System Role Definitions)
-- ------------------------------------------------------------
CREATE TABLE ROLE (
    ROLE_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROLE_NAME       VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(255)
);

-- ------------------------------------------------------------
-- 8. ORG_MEMBERS (Tenant Membership Roster)
-- ------------------------------------------------------------
CREATE TABLE ORG_MEMBERS (
    MEMBER_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORGID           VARCHAR2(40) NOT NULL,
    PID             NUMBER NOT NULL,
    MEMBER_STATUS   VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (MEMBER_STATUS IN ('ACTIVE', 'SUSPENDED', 'PENDING')),
    JOINED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_MEMBER_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE,
    CONSTRAINT UQ_ORG_PID UNIQUE (ORGID, PID)
);

-- ------------------------------------------------------------
-- 9. ORG_SCOPE (Hierarchical Organizational Units & Branches)
-- ------------------------------------------------------------
CREATE TABLE ORG_SCOPE (
    SCOPE_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORGID           VARCHAR2(40) NOT NULL,
    SCOPE_NAME      VARCHAR2(100) NOT NULL,
    PARENT_SCOPE_ID NUMBER,
    DESCRIPTION     VARCHAR2(255),
    CONSTRAINT FK_SCOPE_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID) ON DELETE CASCADE,
    CONSTRAINT FK_SCOPE_PARENT FOREIGN KEY (PARENT_SCOPE_ID) REFERENCES ORG_SCOPE(SCOPE_ID) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- 10. MEMBER_ROLES (Scoped Role Assignments)
-- ------------------------------------------------------------
CREATE TABLE MEMBER_ROLES (
    MEMBER_ROLE_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORGID           VARCHAR2(40) NOT NULL,
    PID             NUMBER NOT NULL,
    ROLE_ID         NUMBER NOT NULL,
    ASSIGNED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_MR_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID) ON DELETE CASCADE,
    CONSTRAINT FK_MR_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE,
    CONSTRAINT FK_MR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ORG_PID_ROLE UNIQUE (ORGID, PID, ROLE_ID)
);

-- ------------------------------------------------------------
-- 11. ELECTION / EVENTS (Lifecycle & Window Timeframes)
-- ------------------------------------------------------------
CREATE TABLE ELECTION (
    ELECTION_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORGID           VARCHAR2(40) NOT NULL,
    TITLE           VARCHAR2(160) NOT NULL,
    DESCRIPTION     VARCHAR2(2000),
    STATUS          VARCHAR2(20) DEFAULT 'UPCOMING' 
                    CHECK (STATUS IN ('UPCOMING', 'NOMINATION', 'ACTIVE', 'COMPLETED')),
    START_DATE      TIMESTAMP,
    END_DATE        TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ELECTION_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID) ON DELETE CASCADE
);

-- Synonym providing ER diagram alignment for EVENTS
CREATE OR REPLACE SYNONYM EVENTS FOR ELECTION;

-- ------------------------------------------------------------
-- 12. CANDIDATE (Candidate Roster & Scrutiny)
-- ------------------------------------------------------------
CREATE TABLE CANDIDATE (
    CANDIDATE_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER NOT NULL,
    PID             NUMBER NOT NULL,
    POSITION        VARCHAR2(100) NOT NULL,
    MANIFESTO       VARCHAR2(1500),
    STATUS          VARCHAR2(20) DEFAULT 'PENDING' 
                    CHECK (STATUS IN ('PENDING', 'ACTIVE', 'REJECTED')),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CAND_ELEC FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CAND_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE,
    CONSTRAINT UQ_CAND_ELEC_PID UNIQUE (ELECTION_ID, PID)
);

-- Synonym providing ER diagram alignment for CANDIDATES
CREATE OR REPLACE SYNONYM CANDIDATES FOR CANDIDATE;

-- ------------------------------------------------------------
-- 13. EVENT_PARTICIPANTS (Voter Roll Whitelist & Entitlement)
-- ------------------------------------------------------------
CREATE TABLE EVENT_PARTICIPANTS (
    PARTICIPANT_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER NOT NULL,
    PID             NUMBER NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'ELIGIBLE' 
                    CHECK (STATUS IN ('ELIGIBLE', 'VOTED', 'REVOKED')),
    REGISTERED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EP_ELEC FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_EP_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE,
    CONSTRAINT UQ_ELEC_VOTER UNIQUE (ELECTION_ID, PID)
);

-- ------------------------------------------------------------
-- 14. VOTE (Decoupled Anonymous Ballot Box — PID Omitted)
-- ------------------------------------------------------------
CREATE TABLE VOTE (
    VOTE_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER NOT NULL,
    CANDIDATE_ID    NUMBER NOT NULL,
    VOTED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_VOTE_ELEC FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VOTE_CAND FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID) ON DELETE CASCADE
);

-- Synonym providing ER diagram alignment for VOTES
CREATE OR REPLACE SYNONYM VOTES FOR VOTE;

-- ------------------------------------------------------------
-- 15. VOTE_RESULTS (Aggregated Standing Records)
-- ------------------------------------------------------------
CREATE TABLE VOTE_RESULTS (
    RESULT_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER NOT NULL,
    CANDIDATE_ID    NUMBER NOT NULL,
    TOTAL_VOTES     NUMBER DEFAULT 0 NOT NULL,
    PERCENTAGE      NUMBER(5,2) DEFAULT 0.00,
    TALLIED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_VR_ELEC FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VR_CAND FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ELEC_CAND_RESULT UNIQUE (ELECTION_ID, CANDIDATE_ID)
);

-- ------------------------------------------------------------
-- 16. AUDIT_LOGS (System Accountability Trail)
-- ------------------------------------------------------------
CREATE TABLE AUDIT_LOGS (
    LOG_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER,
    ACTION_TYPE     VARCHAR2(100) NOT NULL,
    DETAILS         VARCHAR2(1000),
    ACTION_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_AUDIT_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- 17. FRAUD_LOGS (Security Signal & Anomaly Detection Trail)
-- ------------------------------------------------------------
CREATE TABLE FRAUD_LOGS (
    FRAUD_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER,
    FRAUD_TYPE      VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    DETECTED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_FRAUD_PID FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE SET NULL
);

-- ============================================================
-- SEED DATA: Mandatory Roles for Authentication & RBAC
-- ============================================================
INSERT INTO ROLE (ROLE_NAME, DESCRIPTION) VALUES ('ADMIN', 'Global platform administrator');
INSERT INTO ROLE (ROLE_NAME, DESCRIPTION) VALUES ('ORGANIZER', 'Manages elections and candidates for an organization');
INSERT INTO ROLE (ROLE_NAME, DESCRIPTION) VALUES ('VOTER', 'Standard registered voting member');

COMMIT;