-- ============================================================
-- VoteCore: Relational Database Schema (Oracle Database)
-- Mapped from Live Environment Definitions
-- ============================================================

-- ------------------------------------------------------------
-- 1. UACCOUNT
-- ------------------------------------------------------------
CREATE TABLE UACCOUNT (
    PID             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME      VARCHAR2(50) NOT NULL,
    MIDDLE_NAME     VARCHAR2(50),
    LAST_NAME       VARCHAR2(50) NOT NULL,
    MOBILE          VARCHAR2(10),
    EMAIL           VARCHAR2(100),
    COUNTRY         VARCHAR2(32),
    STATE           VARCHAR2(32),
    CREATED_AT      TIMESTAMP(6),
    PASSWORD_HASH   VARCHAR2(100),
    IS_ACTIVE       NUMBER(1)
);

-- ------------------------------------------------------------
-- 2. GOV_IDENTITY
-- ------------------------------------------------------------
CREATE TABLE GOV_IDENTITY (
    EPIC_ID         VARCHAR2(100) NOT NULL PRIMARY KEY,
    FULL_NAME       VARCHAR2(100) NOT NULL,
    MOBILE          VARCHAR2(10),
    EMAIL           VARCHAR2(100),
    STATE           VARCHAR2(50),
    IS_VERIFIED     NUMBER(1),
    AADHAAR_NO      VARCHAR2(100),
    DOB             DATE,
    PID             NUMBER,
    CONSTRAINT FK_GOV_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 3. IDENTITY_WALLET
-- ------------------------------------------------------------
CREATE TABLE IDENTITY_WALLET (
    WALLET_ID       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER(19) NOT NULL,
    IDENTITY_TYPE   VARCHAR2(20) NOT NULL,
    EPIC_ID         VARCHAR2(100),
    CREATED_AT      TIMESTAMP(6),
    CONSTRAINT FK_WALLET_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE,
    CONSTRAINT FK_WALLET_GOV FOREIGN KEY (EPIC_ID) REFERENCES GOV_IDENTITY(EPIC_ID) ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- 4. OTP_VERIFICATION
-- ------------------------------------------------------------
CREATE TABLE OTP_VERIFICATION (
    OTP_ID          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER(19) NOT NULL,
    OTP_CODE        VARCHAR2(10) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    EXPIRES_AT      TIMESTAMP(6) NOT NULL,
    VERIFIED        NUMBER(1),
    ATTEMPTS        NUMBER(3),
    CONSTRAINT FK_OTP_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 5. USER_SESSIONS
-- ------------------------------------------------------------
CREATE TABLE USER_SESSIONS (
    SESSION_ID      VARCHAR2(100) NOT NULL PRIMARY KEY,
    PID             NUMBER(19) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    EXPIRES_AT      TIMESTAMP(6) NOT NULL,
    IS_ACTIVE       NUMBER(1),
    CONSTRAINT FK_SESSION_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 6. ORGANIZATION
-- ------------------------------------------------------------
CREATE TABLE ORGANIZATION (
    ORGID           VARCHAR2(20) NOT NULL PRIMARY KEY,
    ORG_NAME        VARCHAR2(100) NOT NULL,
    ORG_EMAIL       VARCHAR2(100),
    IS_ACTIVE       NUMBER(1),
    IS_DELETED      NUMBER(1),
    CREATED_AT      TIMESTAMP(6)
);

-- ------------------------------------------------------------
-- 7. ROLE
-- ------------------------------------------------------------
CREATE TABLE ROLE (
    ROLE_ID         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROLE_NAME       VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR2(200)
);

-- ------------------------------------------------------------
-- 8. ORG_MEMBERS
-- ------------------------------------------------------------
CREATE TABLE ORG_MEMBERS (
    ORGID           VARCHAR2(20) NOT NULL,
    PID             NUMBER(19) NOT NULL,
    JOINED_AT       TIMESTAMP(6),
    MEMBER_STATUS   VARCHAR2(20),
    PRIMARY KEY (ORGID, PID),
    CONSTRAINT FK_MEMBER_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 9. MEMBER_ROLES
-- ------------------------------------------------------------
CREATE TABLE MEMBER_ROLES (
    ORGID           VARCHAR2(20) NOT NULL,
    PID             NUMBER(19) NOT NULL,
    ROLE_ID         NUMBER(10) NOT NULL,
    ASSIGNED_AT     TIMESTAMP(6),
    PRIMARY KEY (ORGID, PID, ROLE_ID),
    CONSTRAINT FK_MR_MEMBER FOREIGN KEY (ORGID, PID) REFERENCES ORG_MEMBERS(ORGID, PID) ON DELETE CASCADE,
    CONSTRAINT FK_MR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 10. ELECTION
-- ------------------------------------------------------------
CREATE TABLE ELECTION (
    ELECTION_ID     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORGID           VARCHAR2(20) NOT NULL,
    TITLE           VARCHAR2(150) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    START_DATE      TIMESTAMP(6) NOT NULL,
    END_DATE        TIMESTAMP(6) NOT NULL,
    STATUS          VARCHAR2(20),
    CREATED_AT      TIMESTAMP(6),
    CONSTRAINT FK_ELECTION_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 11. CANDIDATE
-- ------------------------------------------------------------
CREATE TABLE CANDIDATE (
    CANDIDATE_ID    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER(10) NOT NULL,
    PID             NUMBER(19) NOT NULL,
    POSITION        VARCHAR2(50) NOT NULL,
    MANIFESTO       VARCHAR2(1000),
    STATUS          VARCHAR2(20),
    CREATED_AT      TIMESTAMP(6),
    CONSTRAINT FK_CANDIDATE_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CANDIDATE_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 12. VOTE_RESULTS
-- ------------------------------------------------------------
CREATE TABLE VOTE_RESULTS (
    RESULT_ID       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER(10) NOT NULL,
    CANDIDATE_ID    NUMBER(10) NOT NULL,
    VOTE_COUNT      NUMBER(10),
    LAST_UPDATED    TIMESTAMP(6),
    CONSTRAINT FK_RESULT_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESULT_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 13. AUDIT_LOGS
-- ------------------------------------------------------------
CREATE TABLE AUDIT_LOGS (
    LOG_ID          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER(19) NOT NULL,
    ACTION_TYPE     VARCHAR2(50) NOT NULL,
    ACTION_TIME     TIMESTAMP(6),
    DETAILS         VARCHAR2(500),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 14. FRAUD_LOGS
-- ------------------------------------------------------------
CREATE TABLE FRAUD_LOGS (
    FRAUD_ID        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PID             NUMBER(19),
    ELECTION_ID     NUMBER(10),
    FRAUD_TYPE      VARCHAR2(50) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    DETECTED_AT     TIMESTAMP(6),
    STATUS          VARCHAR2(20),
    CONSTRAINT FK_FRAUD_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE SET NULL,
    CONSTRAINT FK_FRAUD_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 15. EVENT_PARTICIPANTS
-- ------------------------------------------------------------
CREATE TABLE EVENT_PARTICIPANTS (
    ELECTION_ID     NUMBER(10) NOT NULL,
    PID             NUMBER(19) NOT NULL,
    STATUS          VARCHAR2(20),
    JOINED_AT       TIMESTAMP(6),
    PRIMARY KEY (ELECTION_ID, PID),
    CONSTRAINT FK_EP_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_EP_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 16. VOTE
-- ------------------------------------------------------------
CREATE TABLE VOTE (
    VOTE_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ELECTION_ID     NUMBER NOT NULL,
    CANDIDATE_ID    NUMBER NOT NULL,
    VOTED_AT        TIMESTAMP(6),
    CONSTRAINT FK_VOTE_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VOTE_CANDIDATE FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID) ON DELETE CASCADE
);