-- ============================================================
-- 1. CORE ENTITIES (No Dependencies)
-- ============================================================

CREATE TABLE UACCOUNT (
    PID NUMBER(19) NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    MIDDLE_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50) NOT NULL,
    MOBILE VARCHAR2(10),
    EMAIL VARCHAR2(100),
    COUNTRY VARCHAR2(32),
    STATE VARCHAR2(32),
    CREATED_AT TIMESTAMP(6),
    PASSWORD_HASH VARCHAR2(100),
    IS_ACTIVE NUMBER(1),
    CONSTRAINT PK_UACCOUNT PRIMARY KEY (PID),
    CONSTRAINT UQ_UACCOUNT_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_UACCOUNT_MOBILE UNIQUE (MOBILE)
);

CREATE TABLE ORGANIZATION (
    ORGID VARCHAR2(20) NOT NULL,
    ORG_NAME VARCHAR2(100) NOT NULL,
    ORG_EMAIL VARCHAR2(100),
    IS_ACTIVE NUMBER(1),
    IS_DELETED NUMBER(1),
    CREATED_AT TIMESTAMP(6),
    CONSTRAINT PK_ORGANIZATION PRIMARY KEY (ORGID),
    CONSTRAINT UQ_ORG_EMAIL UNIQUE (ORG_EMAIL)
);


-- ============================================================
-- 2. IDENTITY & AUTHENTICATION (Depends on UACCOUNT)
-- ============================================================

CREATE TABLE GOV_IDENTITY (
    EPIC_ID VARCHAR2(100) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    MOBILE VARCHAR2(10),
    EMAIL VARCHAR2(100),
    STATE VARCHAR2(50),
    IS_VERIFIED NUMBER(1),
    AADHAAR_NO VARCHAR2(100),
    DOB DATE,
    PID NUMBER,
    CONSTRAINT PK_GOV_IDENTITY PRIMARY KEY (EPIC_ID),
    CONSTRAINT FK_GOV_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID)
);

CREATE TABLE IDENTITY_WALLET (
    WALLET_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    IDENTITY_TYPE VARCHAR2(20) NOT NULL,
    EPIC_ID VARCHAR2(100),
    CREATED_AT TIMESTAMP(6),
    CONSTRAINT PK_IDENTITY_WALLET PRIMARY KEY (WALLET_ID),
    CONSTRAINT FK_WALLET_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_WALLET_GOV FOREIGN KEY (EPIC_ID) REFERENCES GOV_IDENTITY(EPIC_ID)
);

CREATE TABLE OTP_VERIFICATION (
    OTP_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    OTP_CODE VARCHAR2(10) NOT NULL,
    CREATED_AT TIMESTAMP(6),
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    VERIFIED NUMBER(1),
    ATTEMPTS NUMBER(3),
    OTP_CODE_HASH VARCHAR2(255),
    CONSTRAINT PK_OTP_VERIFICATION PRIMARY KEY (OTP_ID),
    CONSTRAINT FK_OTP_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID)
);

CREATE TABLE USER_SESSIONS (
    SESSION_ID VARCHAR2(100) NOT NULL,
    PID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP(6),
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    IS_ACTIVE NUMBER(1) NOT NULL,
    IP_ADDRESS VARCHAR2(64),
    USER_AGENT VARCHAR2(500),
    LAST_SEEN_AT TIMESTAMP(6),
    CONSTRAINT PK_USER_SESSIONS PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_SESSION_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID)
);


-- ============================================================
-- 3. ELECTION CORE (Depends on ORGANIZATION & UACCOUNT)
-- ============================================================

CREATE TABLE ELECTION (
    ELECTION_ID NUMBER(10) NOT NULL,
    ORGID VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    START_DATE TIMESTAMP(6) NOT NULL,
    END_DATE TIMESTAMP(6) NOT NULL,
    STATUS VARCHAR2(20),
    CREATED_AT TIMESTAMP(6),
    ORGANIZER_PID NUMBER(19),
    ORGANIZER_APPOINTED_AT TIMESTAMP(6),
    ORGANIZER_APPOINTED_BY NUMBER(19),
    ORGANIZER_APP_CLOSE_AT TIMESTAMP(6),
    PARTY_REG_CLOSE_AT TIMESTAMP(6),
    CANDIDATE_JOIN_CLOSE_AT TIMESTAMP(6),
    SCRUTINY_CLOSE_AT TIMESTAMP(6),
    VOTER_ROLL_LOCKED NUMBER(1) NOT NULL,
    VOTER_ROLL_LOCKED_AT TIMESTAMP(6),
    VOTER_ROLL_LOCKED_BY NUMBER(19),
    RESULTS_STATUS VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_ELECTION PRIMARY KEY (ELECTION_ID),
    CONSTRAINT FK_ELECTION_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID),
    CONSTRAINT FK_ELECTION_ORGANIZER FOREIGN KEY (ORGANIZER_PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_ELECTION_ORG_BY FOREIGN KEY (ORGANIZER_APPOINTED_BY) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_ELECTION_ROLL_BY FOREIGN KEY (VOTER_ROLL_LOCKED_BY) REFERENCES UACCOUNT(PID)
);

CREATE TABLE ORGANIZER_APPLICATION (
    APPLICATION_ID NUMBER(10) NOT NULL,
    ELECTION_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SUBMITTED_AT TIMESTAMP(6) NOT NULL,
    REVIEWED_AT TIMESTAMP(6),
    REVIEWED_BY NUMBER(19),
    REASON VARCHAR2(500),
    PRIMARY KEY (APPLICATION_ID),
    CONSTRAINT UQ_ORG_APP_ELECTION_USER UNIQUE (ELECTION_ID, PID),
    CONSTRAINT FK_ORG_APP_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID),
    CONSTRAINT FK_ORG_APP_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_ORG_APP_REVIEWER FOREIGN KEY (REVIEWED_BY) REFERENCES UACCOUNT(PID)
);

CREATE TABLE ELECTION_POSITION (
    POSITION_ID NUMBER(10) NOT NULL,
    ELECTION_ID NUMBER(10) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    DISPLAY_ORDER NUMBER(5) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (POSITION_ID),
    CONSTRAINT UQ_POSITION_ID_ELEC UNIQUE (ELECTION_ID, POSITION_ID),
    CONSTRAINT UQ_POSITION_ELECTION_TITLE UNIQUE (ELECTION_ID, TITLE),
    CONSTRAINT FK_POSITION_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID)
);


-- ============================================================
-- 4. PARTIES & NOMINATIONS
-- ============================================================

CREATE TABLE ELECTION_PARTY (
    ELECTION_PARTY_ID NUMBER(10) NOT NULL,
    ELECTION_ID NUMBER(10) NOT NULL,
    ORGID VARCHAR2(20) NOT NULL,
    LEADER_PID NUMBER(19) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SYMBOL_CODE VARCHAR2(50),
    MANIFESTO VARCHAR2(2000),
    SUBMITTED_AT TIMESTAMP(6) NOT NULL,
    REVIEWED_AT TIMESTAMP(6),
    REVIEWED_BY NUMBER(19),
    REJECTION_REASON VARCHAR2(500),
    PRIMARY KEY (ELECTION_PARTY_ID),
    CONSTRAINT UQ_ELECTION_PARTY_ID_ELEC UNIQUE (ELECTION_ID, ELECTION_PARTY_ID),
    CONSTRAINT UQ_ELECTION_PARTY_ORG UNIQUE (ELECTION_ID, ORGID),
    CONSTRAINT FK_EPARTY_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID),
    CONSTRAINT FK_EPARTY_ORG FOREIGN KEY (ORGID) REFERENCES ORGANIZATION(ORGID),
    CONSTRAINT FK_EPARTY_LEADER FOREIGN KEY (LEADER_PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_EPARTY_REVIEWER FOREIGN KEY (REVIEWED_BY) REFERENCES UACCOUNT(PID)
);

CREATE TABLE ELECTION_PARTY_MEMBER (
    ELECTION_PARTY_ID NUMBER(10) NOT NULL,
    ELECTION_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    MEMBER_ROLE VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    JOINED_AT TIMESTAMP(6) NOT NULL,
    APPROVED_BY NUMBER(19),
    PRIMARY KEY (ELECTION_PARTY_ID, PID),
    CONSTRAINT UQ_EPM_ELECTION_USER UNIQUE (ELECTION_ID, PID),
    CONSTRAINT UQ_EPM_PARTY_ELEC_USER UNIQUE (ELECTION_PARTY_ID, ELECTION_ID, PID),
    CONSTRAINT FK_EPM_PARTY_ELECTION FOREIGN KEY (ELECTION_ID, ELECTION_PARTY_ID) REFERENCES ELECTION_PARTY(ELECTION_ID, ELECTION_PARTY_ID),
    CONSTRAINT FK_EPM_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_EPM_APPROVER FOREIGN KEY (APPROVED_BY) REFERENCES UACCOUNT(PID)
);

CREATE TABLE CANDIDATE (
    CANDIDATE_ID NUMBER(10) NOT NULL,
    ELECTION_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    POSITION VARCHAR2(50) NOT NULL,
    MANIFESTO VARCHAR2(1000),
    STATUS VARCHAR2(20),
    CREATED_AT TIMESTAMP(6),
    ELECTION_PARTY_ID NUMBER(10),
    POSITION_ID NUMBER(10),
    PARTY_APPROVED_AT TIMESTAMP(6),
    ORGANIZER_APPROVED_AT TIMESTAMP(6),
    ORGANIZER_APPROVED_BY NUMBER(19),
    REJECTION_REASON VARCHAR2(500),
    WITHDRAWN_AT TIMESTAMP(6),
    CONSTRAINT PK_CANDIDATE PRIMARY KEY (CANDIDATE_ID),
    CONSTRAINT UQ_CANDIDATE_ELECTION_USER UNIQUE (ELECTION_ID, PID),
    CONSTRAINT UQ_CAND_ID_ELEC_POS UNIQUE (ELECTION_ID, POSITION_ID, CANDIDATE_ID),
    CONSTRAINT FK_CANDIDATE_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID),
    CONSTRAINT FK_CANDIDATE_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_CAND_POSITION FOREIGN KEY (ELECTION_ID, POSITION_ID) REFERENCES ELECTION_POSITION(ELECTION_ID, POSITION_ID),
    CONSTRAINT FK_CAND_APPROVER FOREIGN KEY (ORGANIZER_APPROVED_BY) REFERENCES UACCOUNT(PID)
);


-- ============================================================
-- 5. VOTING LEDGERS & BALLOTS
-- ============================================================

CREATE TABLE EVENT_PARTICIPANTS (
    ELECTION_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    STATUS VARCHAR2(20),
    JOINED_AT TIMESTAMP(6),
    CONSTRAINT PK_EVENT_PARTICIPANTS PRIMARY KEY (ELECTION_ID, PID),
    CONSTRAINT FK_EP_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID),
    CONSTRAINT FK_EP_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID)
);

CREATE TABLE VOTER_POST_STATUS (
    ELECTION_ID NUMBER(10) NOT NULL,
    POSITION_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    VOTED_AT TIMESTAMP(6),
    PRIMARY KEY (ELECTION_ID, POSITION_ID, PID),
    CONSTRAINT FK_VPS_POSITION FOREIGN KEY (ELECTION_ID, POSITION_ID) REFERENCES ELECTION_POSITION(ELECTION_ID, POSITION_ID),
    CONSTRAINT FK_VPS_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID)
);

CREATE TABLE VOTE (
    VOTE_ID NUMBER NOT NULL,
    ELECTION_ID NUMBER NOT NULL,
    CANDIDATE_ID NUMBER NOT NULL,
    VOTED_AT TIMESTAMP(6),
    POSITION_ID NUMBER(10),
    PRIMARY KEY (VOTE_ID),
    CONSTRAINT FK_VOTE_CAND_ELEC_POS FOREIGN KEY (ELECTION_ID, POSITION_ID, CANDIDATE_ID) REFERENCES CANDIDATE(ELECTION_ID, POSITION_ID, CANDIDATE_ID)
);


-- ============================================================
-- 6. SYSTEM LOGGING & SECURITY
-- ============================================================

CREATE TABLE AUDIT_LOGS (
    LOG_ID NUMBER(10) NOT NULL,
    PID NUMBER(19) NOT NULL,
    ACTION_TYPE VARCHAR2(50) NOT NULL,
    ACTION_TIME TIMESTAMP(6),
    DETAILS VARCHAR2(500),
    ENTITY_TYPE VARCHAR2(30),
    ENTITY_ID VARCHAR2(100),
    OLD_VALUE VARCHAR2(1000),
    NEW_VALUE VARCHAR2(1000),
    SESSION_ID VARCHAR2(100),
    IP_ADDRESS VARCHAR2(64),
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID)
);

CREATE TABLE FRAUD_LOGS (
    FRAUD_ID NUMBER(10) NOT NULL,
    PID NUMBER(19),
    ELECTION_ID NUMBER(10),
    FRAUD_TYPE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DETECTED_AT TIMESTAMP(6),
    STATUS VARCHAR2(20),
    SESSION_ID VARCHAR2(100),
    IP_ADDRESS VARCHAR2(64),
    CONSTRAINT PK_FRAUD_LOGS PRIMARY KEY (FRAUD_ID),
    CONSTRAINT FK_FRAUD_USER FOREIGN KEY (PID) REFERENCES UACCOUNT(PID),
    CONSTRAINT FK_FRAUD_ELECTION FOREIGN KEY (ELECTION_ID) REFERENCES ELECTION(ELECTION_ID)
);


-- ============================================================
-- 7. LOOKUP INDEXES
-- These mirror the named, non-constraint indexes in the live database.
-- ============================================================

CREATE INDEX IX_CAND_ELECTION ON CANDIDATE (ELECTION_ID);
CREATE INDEX IX_ELECTION_ORGANIZER ON ELECTION (ORGANIZER_PID);
CREATE INDEX IX_EPARTY_ELECTION_STATUS ON ELECTION_PARTY (ELECTION_ID, STATUS);
CREATE INDEX IX_POSITION_ELECTION ON ELECTION_POSITION (ELECTION_ID);
CREATE INDEX IX_EVENT_PARTICIPANT_PID ON EVENT_PARTICIPANTS (PID);
CREATE INDEX IX_ORG_APP_STATUS ON ORGANIZER_APPLICATION (STATUS, ELECTION_ID);
CREATE UNIQUE INDEX UX_UACCOUNT_EMAIL_CI ON UACCOUNT (LOWER(EMAIL));
CREATE INDEX IX_VOTE_ELECTION ON VOTE (ELECTION_ID);
CREATE INDEX IX_VPS_ELECTION_STATUS ON VOTER_POST_STATUS (ELECTION_ID, STATUS);


-- ============================================================
-- 8. RESULT VIEW
-- Live vote totals grouped by election position and candidate.
-- ============================================================

CREATE OR REPLACE VIEW V_ELECTION_RESULT_BY_POST AS
SELECT
    E.ELECTION_ID,
    E.TITLE AS ELECTION_TITLE,
    POS.POSITION_ID,
    POS.TITLE AS POSITION_TITLE,
    C.CANDIDATE_ID,
    C.PID AS CANDIDATE_PID,
    U.FIRST_NAME || ' ' || U.LAST_NAME AS CANDIDATE_NAME,
    EP.ELECTION_PARTY_ID,
    O.ORG_NAME AS PARTY_NAME,
    COUNT(V.VOTE_ID) AS TOTAL_VOTES
FROM ELECTION E
JOIN ELECTION_POSITION POS
    ON POS.ELECTION_ID = E.ELECTION_ID
JOIN CANDIDATE C
    ON C.ELECTION_ID = POS.ELECTION_ID
   AND C.POSITION_ID = POS.POSITION_ID
JOIN UACCOUNT U
    ON U.PID = C.PID
LEFT JOIN ELECTION_PARTY EP
    ON EP.ELECTION_PARTY_ID = C.ELECTION_PARTY_ID
LEFT JOIN ORGANIZATION O
    ON O.ORGID = EP.ORGID
LEFT JOIN VOTE V
    ON V.ELECTION_ID = C.ELECTION_ID
   AND V.POSITION_ID = C.POSITION_ID
   AND V.CANDIDATE_ID = C.CANDIDATE_ID
GROUP BY
    E.ELECTION_ID, E.TITLE, POS.POSITION_ID, POS.TITLE,
    C.CANDIDATE_ID, C.PID, U.FIRST_NAME, U.LAST_NAME,
    EP.ELECTION_PARTY_ID, O.ORG_NAME;


-- ============================================================
-- 9. INTEGRITY AND AUDIT TRIGGERS
-- Organizer neutrality prevents an appointed organizer from also entering
-- the same election as a candidate, party leader, or party member.
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_CAND_NEUTRALITY
BEFORE INSERT OR UPDATE OF ELECTION_ID, PID ON CANDIDATE
FOR EACH ROW
DECLARE
    V_ORGANIZER_PID ELECTION.ORGANIZER_PID%TYPE;
BEGIN
    SELECT ORGANIZER_PID INTO V_ORGANIZER_PID
    FROM ELECTION
    WHERE ELECTION_ID = :NEW.ELECTION_ID;

    IF V_ORGANIZER_PID = :NEW.PID THEN
        RAISE_APPLICATION_ERROR(-20001, 'The election organizer cannot be a candidate in the same election.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EPARTY_NEUTRALITY
BEFORE INSERT OR UPDATE OF ELECTION_ID, LEADER_PID ON ELECTION_PARTY
FOR EACH ROW
DECLARE
    V_ORGANIZER_PID ELECTION.ORGANIZER_PID%TYPE;
BEGIN
    SELECT ORGANIZER_PID INTO V_ORGANIZER_PID
    FROM ELECTION
    WHERE ELECTION_ID = :NEW.ELECTION_ID;

    IF V_ORGANIZER_PID = :NEW.LEADER_PID THEN
        RAISE_APPLICATION_ERROR(-20002, 'The election organizer cannot lead a party in the same election.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EPM_NEUTRALITY
BEFORE INSERT OR UPDATE OF ELECTION_ID, PID ON ELECTION_PARTY_MEMBER
FOR EACH ROW
DECLARE
    V_ORGANIZER_PID ELECTION.ORGANIZER_PID%TYPE;
BEGIN
    SELECT ORGANIZER_PID INTO V_ORGANIZER_PID
    FROM ELECTION
    WHERE ELECTION_ID = :NEW.ELECTION_ID;

    IF V_ORGANIZER_PID = :NEW.PID THEN
        RAISE_APPLICATION_ERROR(-20003, 'The election organizer cannot join a party in the same election.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_USER
AFTER INSERT OR UPDATE ON UACCOUNT
FOR EACH ROW
DECLARE
    V_PID UACCOUNT.PID%TYPE;
BEGIN
    V_PID := :NEW.PID;
    INSERT INTO AUDIT_LOGS (PID, ACTION_TYPE, ACTION_TIME, DETAILS, ENTITY_TYPE, ENTITY_ID)
    VALUES (
        V_PID,
        'UACCOUNT_' || ORA_SYSEVENT,
        SYSTIMESTAMP,
        'User record changed by database trigger.',
        'UACCOUNT',
        TO_CHAR(V_PID)
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_ELECTION
AFTER INSERT OR UPDATE OR DELETE ON ELECTION
FOR EACH ROW
DECLARE
    V_PID UACCOUNT.PID%TYPE;
    V_ELECTION_ID ELECTION.ELECTION_ID%TYPE;
BEGIN
    IF DELETING THEN
        V_PID := COALESCE(:OLD.ORGANIZER_APPOINTED_BY, :OLD.ORGANIZER_PID);
        V_ELECTION_ID := :OLD.ELECTION_ID;
    ELSE
        V_PID := COALESCE(:NEW.ORGANIZER_APPOINTED_BY, :NEW.ORGANIZER_PID);
        V_ELECTION_ID := :NEW.ELECTION_ID;
    END IF;

    -- A database trigger has no application-session actor for an unassigned
    -- election, so audit only events that have a valid related user.
    IF V_PID IS NOT NULL THEN
        INSERT INTO AUDIT_LOGS (PID, ACTION_TYPE, ACTION_TIME, DETAILS, ENTITY_TYPE, ENTITY_ID)
        VALUES (
            V_PID,
            'ELECTION_' || ORA_SYSEVENT,
            SYSTIMESTAMP,
            'Election record changed by database trigger.',
            'ELECTION',
            TO_CHAR(V_ELECTION_ID)
        );
    END IF;
END;
/
